id: Dotfiles.Config
name: DotfilesConfigurator
author: FDS
objects:
  - type: confirm
    name: withDotfiles
    message: Do you like to install dotfiles?
  - type: input
    name: 'core.dotfiles_location'
    when: !!js/function function(answer) {return answer.withDotfiles === true}
    message: Please provide your dotfiles location (or github)

