Id: Installation.Command.Config
Name: InstallationCommand
Author: FDS
objects:
  - type: list
    name: 'core.installation_command'
    message: "Select preferred installation command"
    choices: [
      "brew",
      "apt",
      "yum",
      "urpmi",
      "yast",
      "apt-get",
      ]

