Id: OS.Config
Name: OsConfigurator
Author: FDS
objects:
  - type: list
    name: 'core.os'
    message: Select Operating System
    choices: [{ name: "OSX", value: "OSX" }, { name: "Linux", value: "Linux" }]

