Id: SHELL.Config
Name: SHELLConfigurator
Author: FDS
objects:
  - type: list
    name: 'core.shell'
    message: Select preferred Shell Environment
    choices: [ "zsh", "bash", "fish" ]
  - type: list
    name: 'core.shell.config.zsh'
    message: Select ZSH installation method
    choices: [ "minimal", "oh-my-zsh", "presto", "custom" ]
  - type: list
    name: 'core.shell.config.bash'
    message: Select BASH installation method
    choices: [ "minimal", "oh-my-bash", "custom" ]
  - type: list
    name: 'core.shell.config.fish'
    message: Select FISH installation method
    choices: [ "minimal", "oh-my-fish", "custom" ]

