Id: SHELL.Config
Name: SHELLConfigurator
Author: FDS
Objects:
  - type: list
    name: Shell
    message: Select preferred Shell Environment
    choices: [ "zsh", "bash", "fish" ]
  - type: list
    name: SHELLInstallation
    when: !!js/function function(answer) {return answer.Shell === "zsh"}
    message: Select ZSH installation method
    choices: [ "minimal", "oh-my-zsh", "presto", "custom" ]
  - type: list
    name: SHELLInstallation
    when: !!js/function function(answer) {return answer.Shell === "bash"}
    message: Select BASH installation method
    choices: [ "minimal", "oh-my-bash", "custom" ]
  - type: list
    name: SHELLInstallation
    when: !!js/function function(answer) {return answer.Shell === "fish"}
    message: Select FISH installation method
    choices: [ "minimal", "oh-my-fish", "custom" ]

