dotfiles installation:
- vim:
    directory: vim
    directories:
      - ~/.config/nvim
      - ~/.vim
    file: vim/vimrc.vim
    files: [~/.vimrc]
- git gitconfig:
    file: git/gitconfig
    files:
      - ~/.gitconfig

- git gitignore:
    file: git/gitignore_global
    files:
      - ~/.gitignore_global

- zsh:
    directory: zsh
    directories:
      - ~/.zsh
    file: zsh/zshenv
    files:
      - ~/.zshenv

- tmux:
    file: tmux/tmux.tmux
    files:
      - ~/.tmux.conf

- fzf:
    directory: fzf
    directories:
      - ~/.fzf

dependencies:
  - git-core
  - git
  - curl
  - wget
  - ssh
  - sshfs
  - httpie
  - tree
  - rofie:
    os:
      name: linux
  - xclip:
    os:
      name: linux
  - pbcopy:
    os:
      name: darwin
      command: custom_install_command install pbcopy
  - tmux
  - tmuxinator
  - pure-prompt:
      os:
        - name: linux
          command: npm install -g pure-prompt
  - java:
    os:
      - name: linux
        command: apt-get install java
      - name: darwin
        command: brew install java
  - oracle:
    os:
      - name: linux
        command: apt-get install oracle
      - name: darwin
        command: brew install oracle
dbs:
  - postgresql
  - [mysql-client, mysql-server, mysql-common]:
  - mongodb
